In [1]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import TfidfVectorizer,HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
df=pd.read_csv('news.csv',index_col=None)
df

title  \
0     Donald Trump Sends Out Embarrassing New Yearâ...   
1     Drunk Bragging Trump Staffer Started Russian ...   
2     Sheriff David Clarke Becomes An Internet Joke...   
3     Trump Is So Obsessed He Even Has Obama’s Na...   
4     Pope Francis Just Called Out Donald Trump Dur...   
..                                                 ...   
500   Trump’s Latest Retweet Is Actually The Best...   
501   WATCH: Kellyanne Conway Very Upset Hillary Cl...   
502   Fox And Friends Completely Panics And Cuts Se...   
503   Paul Ryan Sharpens His Backstabbing Knife, Pr...   
504   Rabbis Cancel Annual Call With President Over...   

                                                  text subject LABEL  
0    Donald Trump just couldn t wish all Americans ...    News  FAKE  
1    House Intelligence Committee Chairman Devin Nu...    News  REAL  
2    On Friday, it was revealed that former Milwauk...    News  FAKE  
3    On Christmas day, Donald Trump announced that ...    News  FAKE  
4    Pope Francis used his annual Christmas Day mes...    News  REAL  
..                                                 ...     ...   ...  
500  In the middle of a Twitter tantrum directed to...    News  FAKE  
501  White House counselor Kellyanne Conway crawled...    News  FAKE  
502  While the right accuses the left of being  sno...    News  FAKE  
503  During Donald Trump s meltdown during his rall...    News  FAKE  
504  Rabbis representing four prominent Jewish orga...    News  FAKE  

[505 rows x 4 columns]

In [4]:
dataset=df.drop("subject",axis=1)

In [5]:
dataset

title  \
0     Donald Trump Sends Out Embarrassing New Yearâ...   
1     Drunk Bragging Trump Staffer Started Russian ...   
2     Sheriff David Clarke Becomes An Internet Joke...   
3     Trump Is So Obsessed He Even Has Obama’s Na...   
4     Pope Francis Just Called Out Donald Trump Dur...   
..                                                 ...   
500   Trump’s Latest Retweet Is Actually The Best...   
501   WATCH: Kellyanne Conway Very Upset Hillary Cl...   
502   Fox And Friends Completely Panics And Cuts Se...   
503   Paul Ryan Sharpens His Backstabbing Knife, Pr...   
504   Rabbis Cancel Annual Call With President Over...   

                                                  text LABEL  
0    Donald Trump just couldn t wish all Americans ...  FAKE  
1    House Intelligence Committee Chairman Devin Nu...  REAL  
2    On Friday, it was revealed that former Milwauk...  FAKE  
3    On Christmas day, Donald Trump announced that ...  FAKE  
4    Pope Francis used his annual Christmas Day mes...  REAL  
..                                                 ...   ...  
500  In the middle of a Twitter tantrum directed to...  FAKE  
501  White House counselor Kellyanne Conway crawled...  FAKE  
502  While the right accuses the left of being  sno...  FAKE  
503  During Donald Trump s meltdown during his rall...  FAKE  
504  Rabbis representing four prominent Jewish orga...  FAKE  

[505 rows x 3 columns]

In [6]:
y=dataset["LABEL"]

In [7]:
y

0      FAKE
1      REAL
2      FAKE
3      FAKE
4      REAL
       ... 
500    FAKE
501    FAKE
502    FAKE
503    FAKE
504    FAKE
Name: LABEL, Length: 505, dtype: object

In [8]:
x=dataset["text"]

In [9]:
x

0      Donald Trump just couldn t wish all Americans ...
1      House Intelligence Committee Chairman Devin Nu...
2      On Friday, it was revealed that former Milwauk...
3      On Christmas day, Donald Trump announced that ...
4      Pope Francis used his annual Christmas Day mes...
                             ...                        
500    In the middle of a Twitter tantrum directed to...
501    White House counselor Kellyanne Conway crawled...
502    While the right accuses the left of being  sno...
503    During Donald Trump s meltdown during his rall...
504    Rabbis representing four prominent Jewish orga...
Name: text, Length: 505, dtype: object

In [10]:
X_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=53)


In [11]:
tfidf= TfidfVectorizer(stop_words='english',max_features=1000) #common used words remove it
X_train_tfidf=tfidf.fit_transform(X_train)#preprocessing/ x_train(input)/model create and predict
print(x)
x_test_tfidf=tfidf.transform(x_test) # change to the vector

0      Donald Trump just couldn t wish all Americans ...
1      House Intelligence Committee Chairman Devin Nu...
2      On Friday, it was revealed that former Milwauk...
3      On Christmas day, Donald Trump announced that ...
4      Pope Francis used his annual Christmas Day mes...
                             ...                        
500    In the middle of a Twitter tantrum directed to...
501    White House counselor Kellyanne Conway crawled...
502    While the right accuses the left of being  sno...
503    During Donald Trump s meltdown during his rall...
504    Rabbis representing four prominent Jewish orga...
Name: text, Length: 505, dtype: object


In [12]:
len(tfidf.get_feature_names_out()) #  total unique values

1000

In [13]:
print(X_train_tfidf.toarray())
      

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:
clf=MultinomialNB()

clf.fit(X_train_tfidf,y_train) #model create/ y_train(output)
pred=clf.predict(x_test_tfidf) # predict
score=metrics.accuracy_score(y_test,pred)
print("accuracy: %0.3f " % score)

cm=metrics.confusion_matrix(y_test,pred,labels=['FAKE','REAL'])

accuracy: 0.826 


In [15]:
from sklearn.metrics import classification_report
report=classification_report(y_test,pred)

In [16]:
print(report)

              precision    recall  f1-score   support

        FAKE       0.83      1.00      0.90       138
        REAL       0.00      0.00      0.00        29

    accuracy                           0.83       167
   macro avg       0.41      0.50      0.45       167
weighted avg       0.68      0.83      0.75       167



In [23]:
dataset["text"][0]

'Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year,  President Angry Pants tweeted.  2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America!  Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this despicable, petty, infantile gibberish? Only Trump! His lack of decency won t ev

In [24]:
X_train_tfidf[[0]]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 101 stored elements and shape (1, 1000)>

In [25]:
tfidf= TfidfVectorizer(stop_words='english',max_features=1000) #common used words remove it
X_train_tfidf=tfidf.fit_transform(X_train)#preprocessing/ x_train(input)/model create and predict


In [26]:
X_train[[0]]

0    Donald Trump just couldn t wish all Americans ...
Name: text, dtype: object

In [27]:
clf.predict(X_train_tfidf[[2]])

array(['FAKE'], dtype='<U4')